export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Pizza Margerita",
    cookTime: "10-25",
    price: 15,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "margerita.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "3",
    name: "Crispy Burger",
    cookTime: "20-30",
    price: 30,
    favorite: false,
    origins: ["america"],
    stars: 4.5,
    imageUrl: "CRISPY-BURGER.jpeg",
    tags: ["FastFood", "Burger", "Lunch"],
  },
  {
    id: "4",
    name: "Beef Burger",
    cookTime: "20-40",
    price: 40,
    favorite: false,
    origins: ["america"],
    stars: 4.5,
    imageUrl: "beef-burger.png",
    tags: ["FastFood", "Burger", "Lunch"],
  },
  {
    id: "5",
    name: "Mashroom Cream Soup",
    cookTime: "30-40",
    price: 16,
    favorite: false,
    origins: ["america"],
    stars: 4.5,
    imageUrl: "mashroom.png",
    tags: ["Soup", "Soup", "Lunch"],
  },
  {
    id: "6",
    name: "Tomato Cream Soup",
    cookTime: "30-40",
    price: 17,
    favorite: false,
    origins: ["america"],
    stars: 4.5,
    imageUrl: "tomato.png",
    tags: ["Soup", "Soup", "Lunch"],
  },
];

export const sample_users = [
  {
    id: 1,
    name: "maria",
    email: "maria@gmail.com",
    password: "maria",
    address: "gh",
    isAdmin: false,
  },
  {
    id: 1,
    name: "ana",
    email: "ana@gmail.com",
    password: "ana",
    address: "gh",
    isAdmin: true,
  },
];
